// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Term = {__proto__:null,NOT:68, AND:70, OR:72}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%^Q`QPOOOtQPO'#CbOOQO'#Ca'#CaO!oQPO'#CgO#gQPO'#ClOOQO'#C`'#C`O#nQPO'#C_OOQO'#Co'#CoOOQO'#C^'#C^O`QPO'#C^O$cQPO'#CrQ`QPOOO%TQPO'#CdOOQO,58|,58|OOQO,59Q,59QO%{QPO'#CiOOQO,59R,59ROOQO,59W,59WO&QQPO,59WO&XQPO'#CmOOQO,58y,58yOOQO,58x,58xOOQO'#Cp'#CpOOQO'#Cq'#CqO`QPO,58xO`QPO,58xOOQO-E6p-E6pOOQO,59O,59OOOQO,59T,59TOOQO1G.r1G.rOOQO,59X,59XOOQO1G.d1G.dO&aQPO1G.d",
  stateData: "'W~OiOSjOSkOSlOS~OVPO[RO^TO_TOoSOrVO~Om[On^OVUX[UX^UX_UXgUXoUXqUXrUXsUXtUXpUX~Om_OVZX[ZX^ZX_ZXgZXoZXqZXrZXsZXtZXpZX~OpaO~P`OqcOVRX[RX^RX_RXgRXoRXrRXsRXtRXpRX~OsfOtgOVfX[fX^fX_fXgfXofXrfXpfX~OXkOVWX[WX^WX_WXgWXoWXqWXrWXsWXtWXpWX~OXlO~OpmO~P`OXnObnO~OsfOVQi[Qi^Qi_QigQioQirQitQipQi~ObXVX~",
  goto: "#bgPPhw!Q!Z!dP!mP!d!ZP!pPP!Z!sP!v#P#T#WWYOSZbQeXQohRpi_WOSXZbhi_UOSXZbhi_TOSXZbhi_QOSXZbhiR]PR`RRdU_XOSXZbhiThYpRiYQZOQbSTjZb",
  nodeNames: "⚠ Query Expression Clause Primitive TermClause FuzzyTerm Term Fuzzy Integer PrefixWildcardTerm PhraseClause Phrase Proximity Regex EntityToken Group Boost Float Not And Or",
  maxTerm: 36,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "/w~RkOX!vXY%eYZ%jZ]!v]^%o^p!vpq%tqr!vrs%ysx!vxy'gyz'lz{'q{!P!v!P!Q'v!Q![)d!]!a!v!b!c,w!c!}!v#O#P#z#Q#R/m#R#o!v#p#q!v#r#s/r#s;'S!v;'S;=`%_<%lO!v~!{_V~OX!vZ]!v^p!vqr!vsx!v{!P!v!Q![!v!]!a!v!c!}!v#O#P#z#R#o!v#p#q!v#s;'S!v;'S;=`%_<%lO!v~#}RO;'S!v;'S;=`$W;=`O!v~$]`V~OX!vZ]!v^p!vqr!vsx!v{!P!v!Q![!v!]!a!v!c!}!v#O#P#z#R#o!v#p#q!v#s;'S!v;'S;=`%_;=`<%l!v<%lO!v~%bP;=`<%l!v~%jOj~~%oOk~~%tOl~~%yOi~~%|VOr%yrs&cs#O%y#O#P&h#P;'S%y;'S;=`'a<%lO%y~&hO[~~&kRO;'S%y;'S;=`&t;=`O%y~&wWOr%yrs&cs#O%y#O#P&h#P;'S%y;'S;=`'a;=`<%l%y<%lO%y~'dP;=`<%l%y~'lOo~~'qOp~~'vOn~~'yVO!P'v!P!Q(`!Q#O'v#O#P(e#P;'S'v;'S;=`)^<%lO'v~(eO^~~(hRO;'S'v;'S;=`(q;=`O'v~(tWO!P'v!P!Q(`!Q#O'v#O#P(e#P;'S'v;'S;=`)^;=`<%l'v<%lO'v~)aP;=`<%l'v~)k`X~V~OX!vZ]!v^p!vqr!vsx!v{!O!v!O!P*m!Q![)d!]!a!v!c!}!v#O#P#z#R#o!v#p#q!v#s;'S!v;'S;=`%_<%lO!v~*r_V~OX!vZ]!v^p!vqr!vsx!v{!P!v!Q![+q!]!a!v!c!}!v#O#P#z#R#o!v#p#q!v#s;'S!v;'S;=`%_<%lO!v~+x_b~V~OX!vZ]!v^p!vqr!vsx!v{!P!v!Q![+q!]!a!v!c!}!v#O#P#z#R#o!v#p#q!v#s;'S!v;'S;=`%_<%lO!v~,zP#o#p,}~-QSO#p-^#r;'S-^;'S;=`/g<%lO-^~-aTO#p-^#p#q-p#r;'S-^;'S;=`/g<%lO-^~-sSO#p.P#r;'S.P;'S;=`/a<%lO.P~.STO#p.P#p#q.c#r;'S.P;'S;=`/a<%lO.P~.fSO#q.r#r;'S.r;'S;=`/Z<%lO.r~.uTO#q.r#q#r/U#r;'S.r;'S;=`/Z<%lO.r~/ZO_~~/^P;=`<%l.r~/dP;=`<%l.P~/jP;=`<%l-^~/rOq~~/wOm~",
  tokenizers: [0],
  topRules: {"Query":[0,1]},
  specialized: [{term: 7, get: (value: keyof typeof spec_Term) => spec_Term[value] || -1}],
  tokenPrec: 279
})
