// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Term = {__proto__:null,NOT:68, AND:70, OR:72}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%^Q`QPOOOtQPO'#CbOOQO'#Ca'#CaO!oQPO'#CgO#gQPO'#ClOOQO'#C`'#C`O#nQPO'#C_OOQO'#Co'#CoOOQO'#C^'#C^O`QPO'#C^O$cQPO'#CrQ`QPOOO%TQPO'#CdOOQO,58|,58|OOQO,59Q,59QO%{QPO'#CiOOQO,59R,59ROOQO,59W,59WO&QQPO,59WO&XQPO'#CmOOQO,58y,58yOOQO,58x,58xOOQO'#Cp'#CpOOQO'#Cq'#CqO`QPO,58xO`QPO,58xOOQO-E6p-E6pOOQO,59O,59OOOQO,59T,59TOOQO1G.r1G.rOOQO,59X,59XOOQO1G.d1G.dO&^QPO1G.d",
  stateData: "'T~OiOSjOSkOSlOS~OVPO[RO^TO_TOoSOrVO~Om[On^OVUX[UX^UX_UXgUXoUXqUXrUXsUXtUXpUX~Om_OVZX[ZX^ZX_ZXgZXoZXqZXrZXsZXtZXpZX~OpaO~P`OqcOVRX[RX^RX_RXgRXoRXrRXsRXtRXpRX~OsfOtgOVfX[fX^fX_fXgfXofXrfXpfX~OXkOVWX[WX^WX_WXgWXoWXqWXrWXsWXtWXpWX~OXlO~OpmO~P`ObnO~OsfOVQi[Qi^Qi_QigQioQirQitQipQi~ObXVX~",
  goto: "#bgPPhw!Q!Z!dP!mP!d!ZP!pPP!Z!sP!v#P#T#WWYOSZbQeXQohRpi_WOSXZbhi_UOSXZbhi_TOSXZbhi_QOSXZbhiR]PR`RRdU_XOSXZbhiThYpRiYQZOQbSTjZb",
  nodeNames: "⚠ Query Expression Clause Primitive TermClause FuzzyTerm Term Fuzzy Integer PrefixWildcardTerm PhraseClause Phrase Proximity Regex EntityToken Group Boost Float Not And Or",
  maxTerm: 36,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "/y~RkOX!vXY%eYZ%jZ]!v]^%o^p!vpq%tqr!vrs%ysx!vxy'gyz'lz{'q{!P!v!P!Q'v!Q![)d!]!a!v!b!c,y!c!}!v#O#P#z#Q#R/o#R#o!v#p#q!v#r#s/t#s;'S!v;'S;=`%_<%lO!v~!{_V~OX!vZ]!v^p!vqr!vsx!v{!P!v!Q![!v!]!a!v!c!}!v#O#P#z#R#o!v#p#q!v#s;'S!v;'S;=`%_<%lO!v~#}RO;'S!v;'S;=`$W;=`O!v~$]`V~OX!vZ]!v^p!vqr!vsx!v{!P!v!Q![!v!]!a!v!c!}!v#O#P#z#R#o!v#p#q!v#s;'S!v;'S;=`%_;=`<%l!v<%lO!v~%bP;=`<%l!v~%jOj~~%oOk~~%tOl~~%yOi~~%|VOr%yrs&cs#O%y#O#P&h#P;'S%y;'S;=`'a<%lO%y~&hO[~~&kRO;'S%y;'S;=`&t;=`O%y~&wWOr%yrs&cs#O%y#O#P&h#P;'S%y;'S;=`'a;=`<%l%y<%lO%y~'dP;=`<%l%y~'lOo~~'qOp~~'vOn~~'yVO!P'v!P!Q(`!Q#O'v#O#P(e#P;'S'v;'S;=`)^<%lO'v~(eO^~~(hRO;'S'v;'S;=`(q;=`O'v~(tWO!P'v!P!Q(`!Q#O'v#O#P(e#P;'S'v;'S;=`)^;=`<%l'v<%lO'v~)aP;=`<%l'v~)m`b~X~V~OX!vZ]!v^p!vqr!vsx!v{!O!v!O!P*o!Q![)d!]!a!v!c!}!v#O#P#z#R#o!v#p#q!v#s;'S!v;'S;=`%_<%lO!v~*t_V~OX!vZ]!v^p!vqr!vsx!v{!P!v!Q![+s!]!a!v!c!}!v#O#P#z#R#o!v#p#q!v#s;'S!v;'S;=`%_<%lO!v~+z_b~V~OX!vZ]!v^p!vqr!vsx!v{!P!v!Q![+s!]!a!v!c!}!v#O#P#z#R#o!v#p#q!v#s;'S!v;'S;=`%_<%lO!v~,|P#o#p-P~-SSO#p-`#r;'S-`;'S;=`/i<%lO-`~-cTO#p-`#p#q-r#r;'S-`;'S;=`/i<%lO-`~-uSO#p.R#r;'S.R;'S;=`/c<%lO.R~.UTO#p.R#p#q.e#r;'S.R;'S;=`/c<%lO.R~.hSO#q.t#r;'S.t;'S;=`/]<%lO.t~.wTO#q.t#q#r/W#r;'S.t;'S;=`/]<%lO.t~/]O_~~/`P;=`<%l.t~/fP;=`<%l.R~/lP;=`<%l-`~/tOq~~/yOm~",
  tokenizers: [0],
  topRules: {"Query":[0,1]},
  specialized: [{term: 7, get: (value: keyof typeof spec_Term) => spec_Term[value] || -1}],
  tokenPrec: 276
})
