// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Term = {__proto__:null,NOT:66, AND:68, OR:70}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%^Q`QPOOOqQPO'#CbOOQO'#Ca'#CaO!iQPO'#CgO#^QPO'#CkOOQO'#C`'#C`O#eQPO'#C_OOQO'#Cn'#CnOOQO'#C^'#C^O`QPO'#C^O$VQPO'#CqQ`QPOOO$tQPO'#CdOOQO,58|,58|OOQO,59Q,59QO%iQPO'#CiOOQO,59R,59ROOQO,59V,59VO%nQPO,59VO%uQPO'#ClOOQO,58y,58yOOQO,58x,58xOOQO'#Co'#CoOOQO'#Cp'#CpO`QPO,58xO`QPO,58xOOQO-E6o-E6oOOQO,59O,59OOOQO,59T,59TOOQO1G.q1G.qOOQO,59W,59WOOQO1G.d1G.dO%zQPO1G.d",
  stateData: "&n~OhOSiOSjOSkOS~OVPO[RO^TOnSOqVO~Ol[Om^OVUX[UX^UXfUXnUXpUXqUXrUXsUXoUX~Ol_OVZX[ZX^ZXfZXnZXpZXqZXrZXsZXoZX~OoaO~P`OpcOVRX[RX^RXfRXnRXqRXrRXsRXoRX~OrfOsgOVeX[eX^eXfeXneXqeXoeX~OXkOVWX[WX^WXfWXnWXpWXqWXrWXsWXoWX~OXlO~OomO~P`OanO~OrfOVQi[Qi^QifQinQiqQisQioQi~OaXVX~",
  goto: "#afPPgv!P!Y!cP!lP!c!YP!oP!Y!rP!u#O#S#VWYOSZbQeXQohRpi_WOSXZbhi_UOSXZbhi_TOSXZbhi_QOSXZbhiR]PR`RRdU_XOSXZbhiThYpRiYQZOQbSTjZb",
  nodeNames: "⚠ Query Expression Clause Primitive TermClause FuzzyTerm Term Fuzzy Integer PrefixWildcardTerm PhraseClause Phrase Proximity Regex Group Boost Float Not And Or",
  maxTerm: 35,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "-Q~RjOX!sXY%bYZ%gZ]!s]^%l^p!spq%qqr!srs%vsx!sxy'dyz'iz{'n{!P!s!P!Q's!Q![)a!]!a!s!b!}!s#O#P#w#Q#R,v#R#o!s#p#q!s#r#s,{#s;'S!s;'S;=`%[<%lO!s~!x_V~OX!sZ]!s^p!sqr!ssx!s{!P!s!Q![!s!]!a!s!b!}!s#O#P#w#R#o!s#p#q!s#s;'S!s;'S;=`%[<%lO!s~#zRO;'S!s;'S;=`$T;=`O!s~$Y`V~OX!sZ]!s^p!sqr!ssx!s{!P!s!Q![!s!]!a!s!b!}!s#O#P#w#R#o!s#p#q!s#s;'S!s;'S;=`%[;=`<%l!s<%lO!s~%_P;=`<%l!s~%gOi~~%lOj~~%qOk~~%vOh~~%yVOr%vrs&`s#O%v#O#P&e#P;'S%v;'S;=`'^<%lO%v~&eO[~~&hRO;'S%v;'S;=`&q;=`O%v~&tWOr%vrs&`s#O%v#O#P&e#P;'S%v;'S;=`'^;=`<%l%v<%lO%v~'aP;=`<%l%v~'iOn~~'nOo~~'sOm~~'vVO!P's!P!Q(]!Q#O's#O#P(b#P;'S's;'S;=`)Z<%lO's~(bO^~~(eRO;'S's;'S;=`(n;=`O's~(qWO!P's!P!Q(]!Q#O's#O#P(b#P;'S's;'S;=`)Z;=`<%l's<%lO's~)^P;=`<%l's~)j`a~X~V~OX!sZ]!s^p!sqr!ssx!s{!O!s!O!P*l!Q![)a!]!a!s!b!}!s#O#P#w#R#o!s#p#q!s#s;'S!s;'S;=`%[<%lO!s~*q_V~OX!sZ]!s^p!sqr!ssx!s{!P!s!Q![+p!]!a!s!b!}!s#O#P#w#R#o!s#p#q!s#s;'S!s;'S;=`%[<%lO!s~+w_a~V~OX!sZ]!s^p!sqr!ssx!s{!P!s!Q![+p!]!a!s!b!}!s#O#P#w#R#o!s#p#q!s#s;'S!s;'S;=`%[<%lO!s~,{Op~~-QOl~",
  tokenizers: [0],
  topRules: {"Query":[0,1]},
  specialized: [{term: 7, get: (value: keyof typeof spec_Term) => spec_Term[value] || -1}],
  tokenPrec: 255
})
